<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `archive`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class ArchiveRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $archiveProEdition,
        public readonly ?string $archiveStyleSet,
        public readonly ?string $archiveScoresheet,
        public readonly ?string $archiveSuffix,
        public readonly ?int $archiveWinnerMethod,
        public readonly ?string $archiveDisplayWinners,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            archiveProEdition: isset($row['archiveProEdition']) ? (int) $row['archiveProEdition'] : null,
            archiveStyleSet: isset($row['archiveStyleSet']) ? (string) $row['archiveStyleSet'] : null,
            archiveScoresheet: isset($row['archiveScoresheet']) ? (string) $row['archiveScoresheet'] : null,
            archiveSuffix: isset($row['archiveSuffix']) ? (string) $row['archiveSuffix'] : null,
            archiveWinnerMethod: isset($row['archiveWinnerMethod']) ? (int) $row['archiveWinnerMethod'] : null,
            archiveDisplayWinners: isset($row['archiveDisplayWinners']) ? (string) $row['archiveDisplayWinners'] : null,
        );
    }

}
