<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `bcoem_sys`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class BcoemSysRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $version,
        public readonly ?string $versionDate,
        public readonly ?string $dataCheck,
        public readonly ?int $setup,
        public readonly ?int $setupLastStep,
        public readonly ?string $updateSummary,
        public readonly ?string $updateDate,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            version: isset($row['version']) ? (string) $row['version'] : null,
            versionDate: isset($row['version_date']) ? (string) $row['version_date'] : null,
            dataCheck: isset($row['data_check']) ? (string) $row['data_check'] : null,
            setup: isset($row['setup']) ? (int) $row['setup'] : null,
            setupLastStep: isset($row['setup_last_step']) ? (int) $row['setup_last_step'] : null,
            updateSummary: isset($row['update_summary']) ? (string) $row['update_summary'] : null,
            updateDate: isset($row['update_date']) ? (string) $row['update_date'] : null,
        );
    }

}
