<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `brewer`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class BrewerRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $uid,
        public readonly ?string $brewerFirstName,
        public readonly ?string $brewerLastName,
        public readonly ?string $brewerAddress,
        public readonly ?string $brewerCity,
        public readonly ?string $brewerState,
        public readonly ?string $brewerZip,
        public readonly ?string $brewerCountry,
        public readonly ?string $brewerPhone1,
        public readonly ?string $brewerPhone2,
        public readonly ?string $brewerClubs,
        public readonly ?string $brewerEmail,
        public readonly ?string $brewerStaff,
        public readonly ?string $brewerSteward,
        public readonly ?string $brewerJudge,
        public readonly ?string $brewerJudgeID,
        public readonly ?string $brewerJudgeMead,
        public readonly ?string $brewerJudgeCider,
        public readonly ?string $brewerJudgeRank,
        public readonly ?string $brewerJudgeLikes,
        public readonly ?string $brewerJudgeDislikes,
        public readonly ?string $brewerJudgeLocation,
        public readonly ?string $brewerStewardLocation,
        public readonly ?string $brewerJudgeExp,
        public readonly ?string $brewerJudgeNotes,
        public readonly ?string $brewerAssignment,
        public readonly ?string $brewerJudgeWaiver,
        public readonly ?string $brewerAHA,
        public readonly ?string $brewerDiscount,
        public readonly ?int $brewerProAm,
        public readonly ?int $brewerDropOff,
        public readonly ?string $brewerBreweryName,
        public readonly ?string $brewerBreweryInfo,
        public readonly ?int $brewerMHP,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            uid: isset($row['uid']) ? (int) $row['uid'] : null,
            brewerFirstName: isset($row['brewerFirstName']) ? (string) $row['brewerFirstName'] : null,
            brewerLastName: isset($row['brewerLastName']) ? (string) $row['brewerLastName'] : null,
            brewerAddress: isset($row['brewerAddress']) ? (string) $row['brewerAddress'] : null,
            brewerCity: isset($row['brewerCity']) ? (string) $row['brewerCity'] : null,
            brewerState: isset($row['brewerState']) ? (string) $row['brewerState'] : null,
            brewerZip: isset($row['brewerZip']) ? (string) $row['brewerZip'] : null,
            brewerCountry: isset($row['brewerCountry']) ? (string) $row['brewerCountry'] : null,
            brewerPhone1: isset($row['brewerPhone1']) ? (string) $row['brewerPhone1'] : null,
            brewerPhone2: isset($row['brewerPhone2']) ? (string) $row['brewerPhone2'] : null,
            brewerClubs: isset($row['brewerClubs']) ? (string) $row['brewerClubs'] : null,
            brewerEmail: isset($row['brewerEmail']) ? (string) $row['brewerEmail'] : null,
            brewerStaff: isset($row['brewerStaff']) ? (string) $row['brewerStaff'] : null,
            brewerSteward: isset($row['brewerSteward']) ? (string) $row['brewerSteward'] : null,
            brewerJudge: isset($row['brewerJudge']) ? (string) $row['brewerJudge'] : null,
            brewerJudgeID: isset($row['brewerJudgeID']) ? (string) $row['brewerJudgeID'] : null,
            brewerJudgeMead: isset($row['brewerJudgeMead']) ? (string) $row['brewerJudgeMead'] : null,
            brewerJudgeCider: isset($row['brewerJudgeCider']) ? (string) $row['brewerJudgeCider'] : null,
            brewerJudgeRank: isset($row['brewerJudgeRank']) ? (string) $row['brewerJudgeRank'] : null,
            brewerJudgeLikes: isset($row['brewerJudgeLikes']) ? (string) $row['brewerJudgeLikes'] : null,
            brewerJudgeDislikes: isset($row['brewerJudgeDislikes']) ? (string) $row['brewerJudgeDislikes'] : null,
            brewerJudgeLocation: isset($row['brewerJudgeLocation']) ? (string) $row['brewerJudgeLocation'] : null,
            brewerStewardLocation: isset($row['brewerStewardLocation']) ? (string) $row['brewerStewardLocation'] : null,
            brewerJudgeExp: isset($row['brewerJudgeExp']) ? (string) $row['brewerJudgeExp'] : null,
            brewerJudgeNotes: isset($row['brewerJudgeNotes']) ? (string) $row['brewerJudgeNotes'] : null,
            brewerAssignment: isset($row['brewerAssignment']) ? (string) $row['brewerAssignment'] : null,
            brewerJudgeWaiver: isset($row['brewerJudgeWaiver']) ? (string) $row['brewerJudgeWaiver'] : null,
            brewerAHA: isset($row['brewerAHA']) ? (string) $row['brewerAHA'] : null,
            brewerDiscount: isset($row['brewerDiscount']) ? (string) $row['brewerDiscount'] : null,
            brewerProAm: isset($row['brewerProAm']) ? (int) $row['brewerProAm'] : null,
            brewerDropOff: isset($row['brewerDropOff']) ? (int) $row['brewerDropOff'] : null,
            brewerBreweryName: isset($row['brewerBreweryName']) ? (string) $row['brewerBreweryName'] : null,
            brewerBreweryInfo: isset($row['brewerBreweryInfo']) ? (string) $row['brewerBreweryInfo'] : null,
            brewerMHP: isset($row['brewerMHP']) ? (int) $row['brewerMHP'] : null,
        );
    }

}
