<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `brewing`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class BrewingRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $brewName,
        public readonly ?string $brewStyle,
        public readonly ?string $brewCategory,
        public readonly ?string $brewCategorySort,
        public readonly ?string $brewSubCategory,
        public readonly ?string $brewBottleDate,
        public readonly ?string $brewDate,
        public readonly ?string $brewYield,
        public readonly ?string $brewInfo,
        public readonly ?string $brewMead1,
        public readonly ?string $brewMead2,
        public readonly ?string $brewMead3,
        public readonly ?string $brewComments,
        public readonly ?string $brewBrewerID,
        public readonly ?string $brewBrewerFirstName,
        public readonly ?string $brewBrewerLastName,
        public readonly ?int $brewPaid,
        public readonly ?float $brewABV,
        public readonly ?string $brewWinnerCat,
        public readonly ?string $brewInfoOptional,
        public readonly ?string $brewAdminNotes,
        public readonly ?string $brewStaffNotes,
        public readonly ?string $brewPossAllergens,
        public readonly ?int $brewReceived,
        public readonly ?string $brewSweetnessLevel,
        public readonly ?string $brewCoBrewer,
        public readonly ?string $brewJudgingNumber,
        public readonly ?string $brewUpdated,
        public readonly ?int $brewConfirmed,
        public readonly ?string $brewBoxNum,
        public readonly ?string $brewJuiceSource,
        public readonly ?string $brewPouring,
        public readonly ?int $brewStyleType,
        public readonly ?string $brewPackaging,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            brewName: isset($row['brewName']) ? (string) $row['brewName'] : null,
            brewStyle: isset($row['brewStyle']) ? (string) $row['brewStyle'] : null,
            brewCategory: isset($row['brewCategory']) ? (string) $row['brewCategory'] : null,
            brewCategorySort: isset($row['brewCategorySort']) ? (string) $row['brewCategorySort'] : null,
            brewSubCategory: isset($row['brewSubCategory']) ? (string) $row['brewSubCategory'] : null,
            brewBottleDate: isset($row['brewBottleDate']) ? (string) $row['brewBottleDate'] : null,
            brewDate: isset($row['brewDate']) ? (string) $row['brewDate'] : null,
            brewYield: isset($row['brewYield']) ? (string) $row['brewYield'] : null,
            brewInfo: isset($row['brewInfo']) ? (string) $row['brewInfo'] : null,
            brewMead1: isset($row['brewMead1']) ? (string) $row['brewMead1'] : null,
            brewMead2: isset($row['brewMead2']) ? (string) $row['brewMead2'] : null,
            brewMead3: isset($row['brewMead3']) ? (string) $row['brewMead3'] : null,
            brewComments: isset($row['brewComments']) ? (string) $row['brewComments'] : null,
            brewBrewerID: isset($row['brewBrewerID']) ? (string) $row['brewBrewerID'] : null,
            brewBrewerFirstName: isset($row['brewBrewerFirstName']) ? (string) $row['brewBrewerFirstName'] : null,
            brewBrewerLastName: isset($row['brewBrewerLastName']) ? (string) $row['brewBrewerLastName'] : null,
            brewPaid: isset($row['brewPaid']) ? (int) $row['brewPaid'] : null,
            brewABV: isset($row['brewABV']) ? (float) $row['brewABV'] : null,
            brewWinnerCat: isset($row['brewWinnerCat']) ? (string) $row['brewWinnerCat'] : null,
            brewInfoOptional: isset($row['brewInfoOptional']) ? (string) $row['brewInfoOptional'] : null,
            brewAdminNotes: isset($row['brewAdminNotes']) ? (string) $row['brewAdminNotes'] : null,
            brewStaffNotes: isset($row['brewStaffNotes']) ? (string) $row['brewStaffNotes'] : null,
            brewPossAllergens: isset($row['brewPossAllergens']) ? (string) $row['brewPossAllergens'] : null,
            brewReceived: isset($row['brewReceived']) ? (int) $row['brewReceived'] : null,
            brewSweetnessLevel: isset($row['brewSweetnessLevel']) ? (string) $row['brewSweetnessLevel'] : null,
            brewCoBrewer: isset($row['brewCoBrewer']) ? (string) $row['brewCoBrewer'] : null,
            brewJudgingNumber: isset($row['brewJudgingNumber']) ? (string) $row['brewJudgingNumber'] : null,
            brewUpdated: isset($row['brewUpdated']) ? (string) $row['brewUpdated'] : null,
            brewConfirmed: isset($row['brewConfirmed']) ? (int) $row['brewConfirmed'] : null,
            brewBoxNum: isset($row['brewBoxNum']) ? (string) $row['brewBoxNum'] : null,
            brewJuiceSource: isset($row['brewJuiceSource']) ? (string) $row['brewJuiceSource'] : null,
            brewPouring: isset($row['brewPouring']) ? (string) $row['brewPouring'] : null,
            brewStyleType: isset($row['brewStyleType']) ? (int) $row['brewStyleType'] : null,
            brewPackaging: isset($row['brewPackaging']) ? (string) $row['brewPackaging'] : null,
        );
    }

}
