<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `contest_info`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class ContestInfoRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $contestName,
        public readonly ?string $contestHost,
        public readonly ?string $contestHostWebsite,
        public readonly ?string $contestHostLocation,
        public readonly ?string $contestRegistrationOpen,
        public readonly ?string $contestRegistrationDeadline,
        public readonly ?string $contestEntryOpen,
        public readonly ?string $contestEntryDeadline,
        public readonly ?string $contestJudgeOpen,
        public readonly ?string $contestJudgeDeadline,
        public readonly ?string $contestAwardsLocation,
        public readonly ?string $contestAwardsLocName,
        public readonly ?string $contestAwardsLocDate,
        public readonly ?string $contestAwardsLocTime,
        public readonly ?string $contestShippingOpen,
        public readonly ?string $contestShippingDeadline,
        public readonly ?float $contestEntryFee,
        public readonly ?float $contestEntryFee2,
        public readonly ?string $contestEntryFeeDiscount,
        public readonly ?string $contestEntryFeeDiscountNum,
        public readonly ?string $contestDropoffOpen,
        public readonly ?string $contestBottles,
        public readonly ?string $contestShippingAddress,
        public readonly ?string $contestShippingName,
        public readonly ?string $contestAwards,
        public readonly ?string $contestLogo,
        public readonly ?string $contestBOSAward,
        public readonly ?string $contestDropoffDeadline,
        public readonly ?int $contestEntryCap,
        public readonly ?string $contestEntryFeePassword,
        public readonly ?float $contestEntryFeePasswordNum,
        public readonly ?string $contestID,
        public readonly ?string $contestCircuit,
        public readonly ?string $contestVolunteers,
        public readonly ?string $contestCheckInPassword,
        public readonly ?string $contestClubs,
        public readonly ?string $contestRules,
        public readonly ?string $contestEntryEditDeadline,
        public readonly ?string $contestWinnerLink,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            contestName: isset($row['contestName']) ? (string) $row['contestName'] : null,
            contestHost: isset($row['contestHost']) ? (string) $row['contestHost'] : null,
            contestHostWebsite: isset($row['contestHostWebsite']) ? (string) $row['contestHostWebsite'] : null,
            contestHostLocation: isset($row['contestHostLocation']) ? (string) $row['contestHostLocation'] : null,
            contestRegistrationOpen: isset($row['contestRegistrationOpen']) ? (string) $row['contestRegistrationOpen'] : null,
            contestRegistrationDeadline: isset($row['contestRegistrationDeadline']) ? (string) $row['contestRegistrationDeadline'] : null,
            contestEntryOpen: isset($row['contestEntryOpen']) ? (string) $row['contestEntryOpen'] : null,
            contestEntryDeadline: isset($row['contestEntryDeadline']) ? (string) $row['contestEntryDeadline'] : null,
            contestJudgeOpen: isset($row['contestJudgeOpen']) ? (string) $row['contestJudgeOpen'] : null,
            contestJudgeDeadline: isset($row['contestJudgeDeadline']) ? (string) $row['contestJudgeDeadline'] : null,
            contestAwardsLocation: isset($row['contestAwardsLocation']) ? (string) $row['contestAwardsLocation'] : null,
            contestAwardsLocName: isset($row['contestAwardsLocName']) ? (string) $row['contestAwardsLocName'] : null,
            contestAwardsLocDate: isset($row['contestAwardsLocDate']) ? (string) $row['contestAwardsLocDate'] : null,
            contestAwardsLocTime: isset($row['contestAwardsLocTime']) ? (string) $row['contestAwardsLocTime'] : null,
            contestShippingOpen: isset($row['contestShippingOpen']) ? (string) $row['contestShippingOpen'] : null,
            contestShippingDeadline: isset($row['contestShippingDeadline']) ? (string) $row['contestShippingDeadline'] : null,
            contestEntryFee: isset($row['contestEntryFee']) ? (float) $row['contestEntryFee'] : null,
            contestEntryFee2: isset($row['contestEntryFee2']) ? (float) $row['contestEntryFee2'] : null,
            contestEntryFeeDiscount: isset($row['contestEntryFeeDiscount']) ? (string) $row['contestEntryFeeDiscount'] : null,
            contestEntryFeeDiscountNum: isset($row['contestEntryFeeDiscountNum']) ? (string) $row['contestEntryFeeDiscountNum'] : null,
            contestDropoffOpen: isset($row['contestDropoffOpen']) ? (string) $row['contestDropoffOpen'] : null,
            contestBottles: isset($row['contestBottles']) ? (string) $row['contestBottles'] : null,
            contestShippingAddress: isset($row['contestShippingAddress']) ? (string) $row['contestShippingAddress'] : null,
            contestShippingName: isset($row['contestShippingName']) ? (string) $row['contestShippingName'] : null,
            contestAwards: isset($row['contestAwards']) ? (string) $row['contestAwards'] : null,
            contestLogo: isset($row['contestLogo']) ? (string) $row['contestLogo'] : null,
            contestBOSAward: isset($row['contestBOSAward']) ? (string) $row['contestBOSAward'] : null,
            contestDropoffDeadline: isset($row['contestDropoffDeadline']) ? (string) $row['contestDropoffDeadline'] : null,
            contestEntryCap: isset($row['contestEntryCap']) ? (int) $row['contestEntryCap'] : null,
            contestEntryFeePassword: isset($row['contestEntryFeePassword']) ? (string) $row['contestEntryFeePassword'] : null,
            contestEntryFeePasswordNum: isset($row['contestEntryFeePasswordNum']) ? (float) $row['contestEntryFeePasswordNum'] : null,
            contestID: isset($row['contestID']) ? (string) $row['contestID'] : null,
            contestCircuit: isset($row['contestCircuit']) ? (string) $row['contestCircuit'] : null,
            contestVolunteers: isset($row['contestVolunteers']) ? (string) $row['contestVolunteers'] : null,
            contestCheckInPassword: isset($row['contestCheckInPassword']) ? (string) $row['contestCheckInPassword'] : null,
            contestClubs: isset($row['contestClubs']) ? (string) $row['contestClubs'] : null,
            contestRules: isset($row['contestRules']) ? (string) $row['contestRules'] : null,
            contestEntryEditDeadline: isset($row['contestEntryEditDeadline']) ? (string) $row['contestEntryEditDeadline'] : null,
            contestWinnerLink: isset($row['contestWinnerLink']) ? (string) $row['contestWinnerLink'] : null,
        );
    }

}
