<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `contacts`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class ContactsRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $contactFirstName,
        public readonly ?string $contactLastName,
        public readonly ?string $contactPosition,
        public readonly ?string $contactEmail,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            contactFirstName: isset($row['contactFirstName']) ? (string) $row['contactFirstName'] : null,
            contactLastName: isset($row['contactLastName']) ? (string) $row['contactLastName'] : null,
            contactPosition: isset($row['contactPosition']) ? (string) $row['contactPosition'] : null,
            contactEmail: isset($row['contactEmail']) ? (string) $row['contactEmail'] : null,
        );
    }

}
