<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `drop_off`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class DropOffRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $dropLocation,
        public readonly ?string $dropLocationName,
        public readonly ?string $dropLocationPhone,
        public readonly ?string $dropLocationWebsite,
        public readonly ?string $dropLocationNotes,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            dropLocation: isset($row['dropLocation']) ? (string) $row['dropLocation'] : null,
            dropLocationName: isset($row['dropLocationName']) ? (string) $row['dropLocationName'] : null,
            dropLocationPhone: isset($row['dropLocationPhone']) ? (string) $row['dropLocationPhone'] : null,
            dropLocationWebsite: isset($row['dropLocationWebsite']) ? (string) $row['dropLocationWebsite'] : null,
            dropLocationNotes: isset($row['dropLocationNotes']) ? (string) $row['dropLocationNotes'] : null,
        );
    }

}
