<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `evaluation`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class EvaluationRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $eid,
        public readonly ?int $uid,
        public readonly ?string $evalToken,
        public readonly ?int $evalJudgeInfo,
        public readonly ?int $evalScoresheet,
        public readonly ?int $evalStyle,
        public readonly ?string $evalSpecialIngredients,
        public readonly ?string $evalOtherNotes,
        public readonly ?int $evalBottle,
        public readonly ?string $evalBottleNotes,
        public readonly ?int $evalAromaScore,
        public readonly ?string $evalAromaChecklist,
        public readonly ?string $evalAromaChecklistDesc,
        public readonly ?string $evalAromaComments,
        public readonly ?int $evalAppearanceScore,
        public readonly ?string $evalAppearanceChecklist,
        public readonly ?string $evalAppearanceChecklistDesc,
        public readonly ?string $evalAppearanceComments,
        public readonly ?int $evalFlavorScore,
        public readonly ?string $evalFlavorChecklist,
        public readonly ?string $evalFlavorChecklistDesc,
        public readonly ?string $evalFlavorComments,
        public readonly ?int $evalMouthfeelScore,
        public readonly ?string $evalMouthfeelChecklist,
        public readonly ?string $evalMouthfeelChecklistDesc,
        public readonly ?string $evalMouthfeelComments,
        public readonly ?int $evalOverallScore,
        public readonly ?string $evalOverallChecklist,
        public readonly ?string $evalOverallChecklistDesc,
        public readonly ?string $evalOverallComments,
        public readonly ?int $evalStyleAccuracy,
        public readonly ?int $evalTechMerit,
        public readonly ?int $evalIntangibles,
        public readonly ?string $evalDescriptors,
        public readonly ?string $evalDrinkability,
        public readonly ?string $evalFlaws,
        public readonly ?int $evalInitialDate,
        public readonly ?int $evalUpdatedDate,
        public readonly ?int $evalTable,
        public readonly ?int $evalFinalScore,
        public readonly ?int $evalMiniBOS,
        public readonly ?string $evalPosition,
        public readonly ?int $evalPlace,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            eid: isset($row['eid']) ? (int) $row['eid'] : null,
            uid: isset($row['uid']) ? (int) $row['uid'] : null,
            evalToken: isset($row['evalToken']) ? (string) $row['evalToken'] : null,
            evalJudgeInfo: isset($row['evalJudgeInfo']) ? (int) $row['evalJudgeInfo'] : null,
            evalScoresheet: isset($row['evalScoresheet']) ? (int) $row['evalScoresheet'] : null,
            evalStyle: isset($row['evalStyle']) ? (int) $row['evalStyle'] : null,
            evalSpecialIngredients: isset($row['evalSpecialIngredients']) ? (string) $row['evalSpecialIngredients'] : null,
            evalOtherNotes: isset($row['evalOtherNotes']) ? (string) $row['evalOtherNotes'] : null,
            evalBottle: isset($row['evalBottle']) ? (int) $row['evalBottle'] : null,
            evalBottleNotes: isset($row['evalBottleNotes']) ? (string) $row['evalBottleNotes'] : null,
            evalAromaScore: isset($row['evalAromaScore']) ? (int) $row['evalAromaScore'] : null,
            evalAromaChecklist: isset($row['evalAromaChecklist']) ? (string) $row['evalAromaChecklist'] : null,
            evalAromaChecklistDesc: isset($row['evalAromaChecklistDesc']) ? (string) $row['evalAromaChecklistDesc'] : null,
            evalAromaComments: isset($row['evalAromaComments']) ? (string) $row['evalAromaComments'] : null,
            evalAppearanceScore: isset($row['evalAppearanceScore']) ? (int) $row['evalAppearanceScore'] : null,
            evalAppearanceChecklist: isset($row['evalAppearanceChecklist']) ? (string) $row['evalAppearanceChecklist'] : null,
            evalAppearanceChecklistDesc: isset($row['evalAppearanceChecklistDesc']) ? (string) $row['evalAppearanceChecklistDesc'] : null,
            evalAppearanceComments: isset($row['evalAppearanceComments']) ? (string) $row['evalAppearanceComments'] : null,
            evalFlavorScore: isset($row['evalFlavorScore']) ? (int) $row['evalFlavorScore'] : null,
            evalFlavorChecklist: isset($row['evalFlavorChecklist']) ? (string) $row['evalFlavorChecklist'] : null,
            evalFlavorChecklistDesc: isset($row['evalFlavorChecklistDesc']) ? (string) $row['evalFlavorChecklistDesc'] : null,
            evalFlavorComments: isset($row['evalFlavorComments']) ? (string) $row['evalFlavorComments'] : null,
            evalMouthfeelScore: isset($row['evalMouthfeelScore']) ? (int) $row['evalMouthfeelScore'] : null,
            evalMouthfeelChecklist: isset($row['evalMouthfeelChecklist']) ? (string) $row['evalMouthfeelChecklist'] : null,
            evalMouthfeelChecklistDesc: isset($row['evalMouthfeelChecklistDesc']) ? (string) $row['evalMouthfeelChecklistDesc'] : null,
            evalMouthfeelComments: isset($row['evalMouthfeelComments']) ? (string) $row['evalMouthfeelComments'] : null,
            evalOverallScore: isset($row['evalOverallScore']) ? (int) $row['evalOverallScore'] : null,
            evalOverallChecklist: isset($row['evalOverallChecklist']) ? (string) $row['evalOverallChecklist'] : null,
            evalOverallChecklistDesc: isset($row['evalOverallChecklistDesc']) ? (string) $row['evalOverallChecklistDesc'] : null,
            evalOverallComments: isset($row['evalOverallComments']) ? (string) $row['evalOverallComments'] : null,
            evalStyleAccuracy: isset($row['evalStyleAccuracy']) ? (int) $row['evalStyleAccuracy'] : null,
            evalTechMerit: isset($row['evalTechMerit']) ? (int) $row['evalTechMerit'] : null,
            evalIntangibles: isset($row['evalIntangibles']) ? (int) $row['evalIntangibles'] : null,
            evalDescriptors: isset($row['evalDescriptors']) ? (string) $row['evalDescriptors'] : null,
            evalDrinkability: isset($row['evalDrinkability']) ? (string) $row['evalDrinkability'] : null,
            evalFlaws: isset($row['evalFlaws']) ? (string) $row['evalFlaws'] : null,
            evalInitialDate: isset($row['evalInitialDate']) ? (int) $row['evalInitialDate'] : null,
            evalUpdatedDate: isset($row['evalUpdatedDate']) ? (int) $row['evalUpdatedDate'] : null,
            evalTable: isset($row['evalTable']) ? (int) $row['evalTable'] : null,
            evalFinalScore: isset($row['evalFinalScore']) ? (int) $row['evalFinalScore'] : null,
            evalMiniBOS: isset($row['evalMiniBOS']) ? (int) $row['evalMiniBOS'] : null,
            evalPosition: isset($row['evalPosition']) ? (string) $row['evalPosition'] : null,
            evalPlace: isset($row['evalPlace']) ? (int) $row['evalPlace'] : null,
        );
    }

}
