<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `judging_locations`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class JudgingLocationsRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $judgingLocType,
        public readonly ?string $judgingDate,
        public readonly ?string $judgingDateEnd,
        public readonly ?string $judgingLocName,
        public readonly ?string $judgingLocation,
        public readonly ?int $judgingRounds,
        public readonly ?string $judgingLocNotes,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            judgingLocType: isset($row['judgingLocType']) ? (int) $row['judgingLocType'] : null,
            judgingDate: isset($row['judgingDate']) ? (string) $row['judgingDate'] : null,
            judgingDateEnd: isset($row['judgingDateEnd']) ? (string) $row['judgingDateEnd'] : null,
            judgingLocName: isset($row['judgingLocName']) ? (string) $row['judgingLocName'] : null,
            judgingLocation: isset($row['judgingLocation']) ? (string) $row['judgingLocation'] : null,
            judgingRounds: isset($row['judgingRounds']) ? (int) $row['judgingRounds'] : null,
            judgingLocNotes: isset($row['judgingLocNotes']) ? (string) $row['judgingLocNotes'] : null,
        );
    }

}
