<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `judging_tables`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class JudgingTablesRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $tableName,
        public readonly ?string $tableStyles,
        public readonly ?int $tableNumber,
        public readonly ?int $tableLocation,
        public readonly ?int $tableEntryLimit,
        public readonly ?string $tableStewards,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            tableName: isset($row['tableName']) ? (string) $row['tableName'] : null,
            tableStyles: isset($row['tableStyles']) ? (string) $row['tableStyles'] : null,
            tableNumber: isset($row['tableNumber']) ? (int) $row['tableNumber'] : null,
            tableLocation: isset($row['tableLocation']) ? (int) $row['tableLocation'] : null,
            tableEntryLimit: isset($row['tableEntryLimit']) ? (int) $row['tableEntryLimit'] : null,
            tableStewards: isset($row['tableStewards']) ? (string) $row['tableStewards'] : null,
        );
    }

}
