<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `judging_preferences`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class JudgingPreferencesRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $jPrefsQueued,
        public readonly ?int $jPrefsFlightEntries,
        public readonly ?int $jPrefsMaxBOS,
        public readonly ?int $jPrefsRounds,
        public readonly ?int $jPrefsCapJudges,
        public readonly ?int $jPrefsCapStewards,
        public readonly ?int $jPrefsBottleNum,
        public readonly ?int $jPrefsJudgingOpen,
        public readonly ?int $jPrefsJudgingClosed,
        public readonly ?int $jPrefsScoresheet,
        public readonly ?int $jPrefsMinWords,
        public readonly ?int $jPrefsScoreDispMax,
        public readonly ?int $jPrefsTablePlanning,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            jPrefsQueued: isset($row['jPrefsQueued']) ? (string) $row['jPrefsQueued'] : null,
            jPrefsFlightEntries: isset($row['jPrefsFlightEntries']) ? (int) $row['jPrefsFlightEntries'] : null,
            jPrefsMaxBOS: isset($row['jPrefsMaxBOS']) ? (int) $row['jPrefsMaxBOS'] : null,
            jPrefsRounds: isset($row['jPrefsRounds']) ? (int) $row['jPrefsRounds'] : null,
            jPrefsCapJudges: isset($row['jPrefsCapJudges']) ? (int) $row['jPrefsCapJudges'] : null,
            jPrefsCapStewards: isset($row['jPrefsCapStewards']) ? (int) $row['jPrefsCapStewards'] : null,
            jPrefsBottleNum: isset($row['jPrefsBottleNum']) ? (int) $row['jPrefsBottleNum'] : null,
            jPrefsJudgingOpen: isset($row['jPrefsJudgingOpen']) ? (int) $row['jPrefsJudgingOpen'] : null,
            jPrefsJudgingClosed: isset($row['jPrefsJudgingClosed']) ? (int) $row['jPrefsJudgingClosed'] : null,
            jPrefsScoresheet: isset($row['jPrefsScoresheet']) ? (int) $row['jPrefsScoresheet'] : null,
            jPrefsMinWords: isset($row['jPrefsMinWords']) ? (int) $row['jPrefsMinWords'] : null,
            jPrefsScoreDispMax: isset($row['jPrefsScoreDispMax']) ? (int) $row['jPrefsScoreDispMax'] : null,
            jPrefsTablePlanning: isset($row['jPrefsTablePlanning']) ? (int) $row['jPrefsTablePlanning'] : null,
        );
    }

}
