<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `judging_scores`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class JudgingScoresRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $eid,
        public readonly ?int $bid,
        public readonly ?int $scoreTable,
        public readonly ?float $scoreEntry,
        public readonly ?float $scorePlace,
        public readonly ?int $scoreType,
        public readonly ?int $scoreMiniBOS,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            eid: isset($row['eid']) ? (int) $row['eid'] : null,
            bid: isset($row['bid']) ? (int) $row['bid'] : null,
            scoreTable: isset($row['scoreTable']) ? (int) $row['scoreTable'] : null,
            scoreEntry: isset($row['scoreEntry']) ? (float) $row['scoreEntry'] : null,
            scorePlace: isset($row['scorePlace']) ? (float) $row['scorePlace'] : null,
            scoreType: isset($row['scoreType']) ? (int) $row['scoreType'] : null,
            scoreMiniBOS: isset($row['scoreMiniBOS']) ? (int) $row['scoreMiniBOS'] : null,
        );
    }

}
