<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `judging_assignments`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class JudgingAssignmentsRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $bid,
        public readonly ?string $assignment,
        public readonly ?int $assignTable,
        public readonly ?int $assignFlight,
        public readonly ?int $assignRound,
        public readonly ?int $assignLocation,
        public readonly ?string $assignRoles,
        public readonly ?int $assignPlanning,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            bid: isset($row['bid']) ? (int) $row['bid'] : null,
            assignment: isset($row['assignment']) ? (string) $row['assignment'] : null,
            assignTable: isset($row['assignTable']) ? (int) $row['assignTable'] : null,
            assignFlight: isset($row['assignFlight']) ? (int) $row['assignFlight'] : null,
            assignRound: isset($row['assignRound']) ? (int) $row['assignRound'] : null,
            assignLocation: isset($row['assignLocation']) ? (int) $row['assignLocation'] : null,
            assignRoles: isset($row['assignRoles']) ? (string) $row['assignRoles'] : null,
            assignPlanning: isset($row['assignPlanning']) ? (int) $row['assignPlanning'] : null,
        );
    }

}
