<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `judging_flights`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class JudgingFlightsRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $flightTable,
        public readonly ?int $flightNumber,
        public readonly ?string $flightEntryID,
        public readonly ?int $flightRound,
        public readonly ?int $flightPlanning,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            flightTable: isset($row['flightTable']) ? (int) $row['flightTable'] : null,
            flightNumber: isset($row['flightNumber']) ? (int) $row['flightNumber'] : null,
            flightEntryID: isset($row['flightEntryID']) ? (string) $row['flightEntryID'] : null,
            flightRound: isset($row['flightRound']) ? (int) $row['flightRound'] : null,
            flightPlanning: isset($row['flightPlanning']) ? (int) $row['flightPlanning'] : null,
        );
    }

}
