<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `mods`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class ModsRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $modName,
        public readonly ?int $modType,
        public readonly ?int $modExtendFunction,
        public readonly ?string $modExtendFunctionAdmin,
        public readonly ?string $modFilename,
        public readonly ?string $modDescription,
        public readonly ?int $modPermission,
        public readonly ?int $modRank,
        public readonly ?int $modDisplayRank,
        public readonly ?int $modEnable,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            modName: isset($row['mod_name']) ? (string) $row['mod_name'] : null,
            modType: isset($row['mod_type']) ? (int) $row['mod_type'] : null,
            modExtendFunction: isset($row['mod_extend_function']) ? (int) $row['mod_extend_function'] : null,
            modExtendFunctionAdmin: isset($row['mod_extend_function_admin']) ? (string) $row['mod_extend_function_admin'] : null,
            modFilename: isset($row['mod_filename']) ? (string) $row['mod_filename'] : null,
            modDescription: isset($row['mod_description']) ? (string) $row['mod_description'] : null,
            modPermission: isset($row['mod_permission']) ? (int) $row['mod_permission'] : null,
            modRank: isset($row['mod_rank']) ? (int) $row['mod_rank'] : null,
            modDisplayRank: isset($row['mod_display_rank']) ? (int) $row['mod_display_rank'] : null,
            modEnable: isset($row['mod_enable']) ? (int) $row['mod_enable'] : null,
        );
    }

}
