<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `special_best_info`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class SpecialBestInfoRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $sbiName,
        public readonly ?string $sbiDescription,
        public readonly ?int $sbiPlaces,
        public readonly ?int $sbiRank,
        public readonly ?int $sbiDisplayPlaces,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            sbiName: isset($row['sbi_name']) ? (string) $row['sbi_name'] : null,
            sbiDescription: isset($row['sbi_description']) ? (string) $row['sbi_description'] : null,
            sbiPlaces: isset($row['sbi_places']) ? (int) $row['sbi_places'] : null,
            sbiRank: isset($row['sbi_rank']) ? (int) $row['sbi_rank'] : null,
            sbiDisplayPlaces: isset($row['sbi_display_places']) ? (int) $row['sbi_display_places'] : null,
        );
    }

}
