<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `special_best_data`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class SpecialBestDataRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $sid,
        public readonly ?int $bid,
        public readonly ?int $eid,
        public readonly ?int $sbdPlace,
        public readonly ?string $sbdComments,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            sid: isset($row['sid']) ? (int) $row['sid'] : null,
            bid: isset($row['bid']) ? (int) $row['bid'] : null,
            eid: isset($row['eid']) ? (int) $row['eid'] : null,
            sbdPlace: isset($row['sbd_place']) ? (int) $row['sbd_place'] : null,
            sbdComments: isset($row['sbd_comments']) ? (string) $row['sbd_comments'] : null,
        );
    }

}
