<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `sponsors`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class SponsorsRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $sponsorName,
        public readonly ?string $sponsorURL,
        public readonly ?string $sponsorImage,
        public readonly ?string $sponsorText,
        public readonly ?string $sponsorLocation,
        public readonly ?int $sponsorLevel,
        public readonly ?int $sponsorEnable,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            sponsorName: isset($row['sponsorName']) ? (string) $row['sponsorName'] : null,
            sponsorURL: isset($row['sponsorURL']) ? (string) $row['sponsorURL'] : null,
            sponsorImage: isset($row['sponsorImage']) ? (string) $row['sponsorImage'] : null,
            sponsorText: isset($row['sponsorText']) ? (string) $row['sponsorText'] : null,
            sponsorLocation: isset($row['sponsorLocation']) ? (string) $row['sponsorLocation'] : null,
            sponsorLevel: isset($row['sponsorLevel']) ? (int) $row['sponsorLevel'] : null,
            sponsorEnable: isset($row['sponsorEnable']) ? (int) $row['sponsorEnable'] : null,
        );
    }

}
