<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `staff`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class StaffRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?int $uid,
        public readonly ?int $staffJudge,
        public readonly ?int $staffJudgeBos,
        public readonly ?int $staffSteward,
        public readonly ?int $staffOrganizer,
        public readonly ?int $staffStaff,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            uid: isset($row['uid']) ? (int) $row['uid'] : null,
            staffJudge: isset($row['staff_judge']) ? (int) $row['staff_judge'] : null,
            staffJudgeBos: isset($row['staff_judge_bos']) ? (int) $row['staff_judge_bos'] : null,
            staffSteward: isset($row['staff_steward']) ? (int) $row['staff_steward'] : null,
            staffOrganizer: isset($row['staff_organizer']) ? (int) $row['staff_organizer'] : null,
            staffStaff: isset($row['staff_staff']) ? (int) $row['staff_staff'] : null,
        );
    }

}
