<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `styles`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class StylesRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $brewStyleGroup,
        public readonly ?string $brewStyleNum,
        public readonly ?string $brewStyle,
        public readonly ?string $brewStyleCategory,
        public readonly ?string $brewStyleVersion,
        public readonly ?string $brewStyleOG,
        public readonly ?string $brewStyleOGMax,
        public readonly ?string $brewStyleFG,
        public readonly ?string $brewStyleFGMax,
        public readonly ?string $brewStyleABV,
        public readonly ?string $brewStyleABVMax,
        public readonly ?string $brewStyleIBU,
        public readonly ?string $brewStyleIBUMax,
        public readonly ?string $brewStyleSRM,
        public readonly ?string $brewStyleSRMMax,
        public readonly ?string $brewStyleType,
        public readonly ?string $brewStyleInfo,
        public readonly ?string $brewStyleLink,
        public readonly ?string $brewStyleActive,
        public readonly ?string $brewStyleOwn,
        public readonly ?int $brewStyleReqSpec,
        public readonly ?int $brewStyleStrength,
        public readonly ?int $brewStyleCarb,
        public readonly ?int $brewStyleSweet,
        public readonly ?string $brewStyleTags,
        public readonly ?string $brewStyleComEx,
        public readonly ?string $brewStyleEntry,
        public readonly ?int $brewStyleAtLimit,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            brewStyleGroup: isset($row['brewStyleGroup']) ? (string) $row['brewStyleGroup'] : null,
            brewStyleNum: isset($row['brewStyleNum']) ? (string) $row['brewStyleNum'] : null,
            brewStyle: isset($row['brewStyle']) ? (string) $row['brewStyle'] : null,
            brewStyleCategory: isset($row['brewStyleCategory']) ? (string) $row['brewStyleCategory'] : null,
            brewStyleVersion: isset($row['brewStyleVersion']) ? (string) $row['brewStyleVersion'] : null,
            brewStyleOG: isset($row['brewStyleOG']) ? (string) $row['brewStyleOG'] : null,
            brewStyleOGMax: isset($row['brewStyleOGMax']) ? (string) $row['brewStyleOGMax'] : null,
            brewStyleFG: isset($row['brewStyleFG']) ? (string) $row['brewStyleFG'] : null,
            brewStyleFGMax: isset($row['brewStyleFGMax']) ? (string) $row['brewStyleFGMax'] : null,
            brewStyleABV: isset($row['brewStyleABV']) ? (string) $row['brewStyleABV'] : null,
            brewStyleABVMax: isset($row['brewStyleABVMax']) ? (string) $row['brewStyleABVMax'] : null,
            brewStyleIBU: isset($row['brewStyleIBU']) ? (string) $row['brewStyleIBU'] : null,
            brewStyleIBUMax: isset($row['brewStyleIBUMax']) ? (string) $row['brewStyleIBUMax'] : null,
            brewStyleSRM: isset($row['brewStyleSRM']) ? (string) $row['brewStyleSRM'] : null,
            brewStyleSRMMax: isset($row['brewStyleSRMMax']) ? (string) $row['brewStyleSRMMax'] : null,
            brewStyleType: isset($row['brewStyleType']) ? (string) $row['brewStyleType'] : null,
            brewStyleInfo: isset($row['brewStyleInfo']) ? (string) $row['brewStyleInfo'] : null,
            brewStyleLink: isset($row['brewStyleLink']) ? (string) $row['brewStyleLink'] : null,
            brewStyleActive: isset($row['brewStyleActive']) ? (string) $row['brewStyleActive'] : null,
            brewStyleOwn: isset($row['brewStyleOwn']) ? (string) $row['brewStyleOwn'] : null,
            brewStyleReqSpec: isset($row['brewStyleReqSpec']) ? (int) $row['brewStyleReqSpec'] : null,
            brewStyleStrength: isset($row['brewStyleStrength']) ? (int) $row['brewStyleStrength'] : null,
            brewStyleCarb: isset($row['brewStyleCarb']) ? (int) $row['brewStyleCarb'] : null,
            brewStyleSweet: isset($row['brewStyleSweet']) ? (int) $row['brewStyleSweet'] : null,
            brewStyleTags: isset($row['brewStyleTags']) ? (string) $row['brewStyleTags'] : null,
            brewStyleComEx: isset($row['brewStyleComEx']) ? (string) $row['brewStyleComEx'] : null,
            brewStyleEntry: isset($row['brewStyleEntry']) ? (string) $row['brewStyleEntry'] : null,
            brewStyleAtLimit: isset($row['brewStyleAtLimit']) ? (int) $row['brewStyleAtLimit'] : null,
        );
    }

}
