<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `style_types`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class StyleTypesRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $styleTypeName,
        public readonly ?string $styleTypeOwn,
        public readonly ?string $styleTypeBOS,
        public readonly ?int $styleTypeBOSMethod,
        public readonly ?string $styleTypeEntryLimit,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            styleTypeName: isset($row['styleTypeName']) ? (string) $row['styleTypeName'] : null,
            styleTypeOwn: isset($row['styleTypeOwn']) ? (string) $row['styleTypeOwn'] : null,
            styleTypeBOS: isset($row['styleTypeBOS']) ? (string) $row['styleTypeBOS'] : null,
            styleTypeBOSMethod: isset($row['styleTypeBOSMethod']) ? (int) $row['styleTypeBOSMethod'] : null,
            styleTypeEntryLimit: isset($row['styleTypeEntryLimit']) ? (string) $row['styleTypeEntryLimit'] : null,
        );
    }

}
