<?php
declare(strict_types=1);

namespace BCOEM\Domain;

/**
 * Typed row for table `users`.
 * Generated by tools/generate_row_types.php — do not edit by hand.
 *
 * @immutable
 */
final readonly class UsersRow
{
    public function __construct(
        public readonly int $id,
        public readonly ?string $userName,
        public readonly ?string $password,
        public readonly ?string $userLevel,
        public readonly ?string $userQuestion,
        public readonly ?string $userQuestionAnswer,
        public readonly ?string $userCreated,
        public readonly ?string $userToken,
        public readonly ?string $userTokenTime,
        public readonly ?int $userFailedLogins,
        public readonly ?string $userFailedLoginTime,
        public readonly ?int $userAdminObfuscate,
    ) {}

    /**
     * Build a row from a raw mysqli/MysqliDb assoc result.
     * Values are cast from DB strings to the declared PHP types.
     *
     * @param array<string, mixed> $row
     */
    public static function fromArray(array $row): self
    {
        return new self(
            id: (int) $row['id'],
            userName: isset($row['user_name']) ? (string) $row['user_name'] : null,
            password: isset($row['password']) ? (string) $row['password'] : null,
            userLevel: isset($row['userLevel']) ? (string) $row['userLevel'] : null,
            userQuestion: isset($row['userQuestion']) ? (string) $row['userQuestion'] : null,
            userQuestionAnswer: isset($row['userQuestionAnswer']) ? (string) $row['userQuestionAnswer'] : null,
            userCreated: isset($row['userCreated']) ? (string) $row['userCreated'] : null,
            userToken: isset($row['userToken']) ? (string) $row['userToken'] : null,
            userTokenTime: isset($row['userTokenTime']) ? (string) $row['userTokenTime'] : null,
            userFailedLogins: isset($row['userFailedLogins']) ? (int) $row['userFailedLogins'] : null,
            userFailedLoginTime: isset($row['userFailedLoginTime']) ? (string) $row['userFailedLoginTime'] : null,
            userAdminObfuscate: isset($row['userAdminObfuscate']) ? (int) $row['userAdminObfuscate'] : null,
        );
    }

}
