<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\ArchiveRow;

/**
 * Typed repository for table `archive`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<ArchiveRow>
 */
final class ArchiveRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'archive';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return ArchiveRow::fromArray($row);
    }
}
