<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\BcoemSysRow;

/**
 * Typed repository for table `bcoem_sys`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<BcoemSysRow>
 */
final class BcoemSysRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'bcoem_sys';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return BcoemSysRow::fromArray($row);
    }
}
