<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\BrewingRow;

/**
 * Typed repository for table `brewing`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<BrewingRow>
 */
final class BrewingRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'brewing';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return BrewingRow::fromArray($row);
    }
}
