<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\BrewerRow;

/**
 * Typed repository for table `brewer`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<BrewerRow>
 */
final class BrewerRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'brewer';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return BrewerRow::fromArray($row);
    }
}
