<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\ContestInfoRow;

/**
 * Typed repository for table `contest_info`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<ContestInfoRow>
 */
final class ContestInfoRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'contest_info';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return ContestInfoRow::fromArray($row);
    }
}
