<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\ContactsRow;

/**
 * Typed repository for table `contacts`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<ContactsRow>
 */
final class ContactsRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'contacts';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return ContactsRow::fromArray($row);
    }
}
