<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\DropOffRow;

/**
 * Typed repository for table `drop_off`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<DropOffRow>
 */
final class DropOffRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'drop_off';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return DropOffRow::fromArray($row);
    }
}
