<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\EvaluationRow;

/**
 * Typed repository for table `evaluation`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<EvaluationRow>
 */
final class EvaluationRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'evaluation';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return EvaluationRow::fromArray($row);
    }
}
