<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\JudgingScoresBosRow;

/**
 * Typed repository for table `judging_scores_bos`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<JudgingScoresBosRow>
 */
final class JudgingScoresBosRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'judging_scores_bos';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return JudgingScoresBosRow::fromArray($row);
    }
}
