<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\JudgingPreferencesRow;

/**
 * Typed repository for table `judging_preferences`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<JudgingPreferencesRow>
 */
final class JudgingPreferencesRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'judging_preferences';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return JudgingPreferencesRow::fromArray($row);
    }
}
