<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\JudgingTablesRow;

/**
 * Typed repository for table `judging_tables`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<JudgingTablesRow>
 */
final class JudgingTablesRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'judging_tables';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return JudgingTablesRow::fromArray($row);
    }
}
