<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\JudgingFlightsRow;

/**
 * Typed repository for table `judging_flights`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<JudgingFlightsRow>
 */
final class JudgingFlightsRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'judging_flights';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return JudgingFlightsRow::fromArray($row);
    }
}
