<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\JudgingLocationsRow;

/**
 * Typed repository for table `judging_locations`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<JudgingLocationsRow>
 */
final class JudgingLocationsRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'judging_locations';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return JudgingLocationsRow::fromArray($row);
    }
}
