<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\JudgingScoresRow;

/**
 * Typed repository for table `judging_scores`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<JudgingScoresRow>
 */
final class JudgingScoresRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'judging_scores';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return JudgingScoresRow::fromArray($row);
    }
}
