<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\JudgingAssignmentsRow;

/**
 * Typed repository for table `judging_assignments`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<JudgingAssignmentsRow>
 */
final class JudgingAssignmentsRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'judging_assignments';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return JudgingAssignmentsRow::fromArray($row);
    }
}
