<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\ModsRow;

/**
 * Typed repository for table `mods`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<ModsRow>
 */
final class ModsRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'mods';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return ModsRow::fromArray($row);
    }
}
