<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\PreferencesRow;

/**
 * Typed repository for table `preferences`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<PreferencesRow>
 */
final class PreferencesRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'preferences';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return PreferencesRow::fromArray($row);
    }
}
