<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\SpecialBestInfoRow;

/**
 * Typed repository for table `special_best_info`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<SpecialBestInfoRow>
 */
final class SpecialBestInfoRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'special_best_info';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return SpecialBestInfoRow::fromArray($row);
    }
}
