<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\SpecialBestDataRow;

/**
 * Typed repository for table `special_best_data`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<SpecialBestDataRow>
 */
final class SpecialBestDataRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'special_best_data';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return SpecialBestDataRow::fromArray($row);
    }
}
