<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\SponsorsRow;

/**
 * Typed repository for table `sponsors`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<SponsorsRow>
 */
final class SponsorsRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'sponsors';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return SponsorsRow::fromArray($row);
    }
}
