<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\StaffRow;

/**
 * Typed repository for table `staff`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<StaffRow>
 */
final class StaffRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'staff';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return StaffRow::fromArray($row);
    }
}
