<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\StyleTypesRow;

/**
 * Typed repository for table `style_types`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<StyleTypesRow>
 */
final class StyleTypesRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'style_types';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return StyleTypesRow::fromArray($row);
    }
}
