<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\StylesRow;

/**
 * Typed repository for table `styles`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<StylesRow>
 */
final class StylesRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'styles';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return StylesRow::fromArray($row);
    }
}
