<?php
declare(strict_types=1);

namespace BCOEM\Repository;

use BCOEM\Domain\UsersRow;

/**
 * Typed repository for table `users`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<UsersRow>
 */
final class UsersRepository extends AbstractRepository
{
    protected function table(): string
    {
        return 'users';
    }

    /**
     * @param array<string, mixed> $row
     */
    protected function hydrate(array $row): object
    {
        return UsersRow::fromArray($row);
    }
}
