ALTER TABLE `contest_info` 
ADD `contestDate4` DATE NULL AFTER `contestDate3` ,
ADD `contestDate5` DATE NULL AFTER `contestDate4`,
ADD `contestJudgingLocName2` VARCHAR( 255 ) NULL AFTER `contestJudgingLocation` ,
ADD `contestJudgingLocation2` TEXT NULL AFTER `contestJudgingLocName2` ,
ADD `contestJudgingLocName3` VARCHAR( 255 ) NULL AFTER `contestJudgingLocation2` ,
ADD `contestJudgingLocation3` TEXT NULL AFTER `contestJudgingLocName3` ,
ADD `contestJudgingLocName4` VARCHAR( 255 ) NULL AFTER `contestJudgingLocation3` ,
ADD `contestJudgingLocation4` TEXT NULL AFTER `contestJudgingLocName4` ,
ADD `contestJudgingLocName5` VARCHAR( 255 ) NULL AFTER `contestJudgingLocation4` ,
ADD `contestJudgingLocation5` TEXT NULL AFTER `contestJudgingLocName5` ,
ADD `contestAwardsLocName` VARCHAR( 255 ) NULL AFTER `contestJudgingLocation5`,
ADD `contestEntryFee2` VARCHAR( 10 ) NULL AFTER `contestEntryFee` ,
ADD `contestEntryFeeDiscount` CHAR( 1 ) NULL AFTER `contestEntryFee2`,
ADD `contestEntryFeeDiscountNum` CHAR( 3 ) NULL AFTER `contestEntryFeeDiscount` ;
