<?php 

if ($row_log['brewCategorySort'] == "01") $styleConvert = "Light Lager";
if ($row_log['brewCategorySort'] == "02") $styleConvert = "Pilsner";
if ($row_log['brewCategorySort'] == "03") $styleConvert = "European Amber Lager";
if ($row_log['brewCategorySort'] == "04") $styleConvert = "Dark Lager";
if ($row_log['brewCategorySort'] == "05") $styleConvert = "Bock";
if ($row_log['brewCategorySort'] == "06") $styleConvert = "Light Hybrid Beer";
if ($row_log['brewCategorySort'] == "07") $styleConvert = "Amber Hybrid Beer";
if ($row_log['brewCategorySort'] == "08") $styleConvert = "English Pale Ale";
if ($row_log['brewCategorySort'] == "09") $styleConvert = "Scottish and Irish Ale";
if ($row_log['brewCategorySort'] == "10") $styleConvert = "American Ale";
if ($row_log['brewCategorySort'] == "11") $styleConvert = "English Brown Ale";
if ($row_log['brewCategorySort'] == "12") $styleConvert = "Porter";
if ($row_log['brewCategorySort'] == "13") $styleConvert = "Stout";
if ($row_log['brewCategorySort'] == "14") $styleConvert = "India Pale Ale (IPA)";
if ($row_log['brewCategorySort'] == "15") $styleConvert = "German Wheat and Rye Beer";
if ($row_log['brewCategorySort'] == "16") $styleConvert = "Belgian and French Ale";
if ($row_log['brewCategorySort'] == "17") $styleConvert = "Sour Ale";
if ($row_log['brewCategorySort'] == "18") $styleConvert = "Belgian Strong Ale";
if ($row_log['brewCategorySort'] == "19") $styleConvert = "Strong Ale";
if ($row_log['brewCategorySort'] == "20") $styleConvert = "Fruit Beer";
if ($row_log['brewCategorySort'] == "21") $styleConvert = "Spice/Herb/Vegatable Beer";
if ($row_log['brewCategorySort'] == "22") $styleConvert = "Smoke-Flavored and Wood-Aged Beer";
if ($row_log['brewCategorySort'] == "23") $styleConvert = "Specialty Beer";
if ($row_log['brewCategorySort'] == "24") $styleConvert = "Traditional Mead";
if ($row_log['brewCategorySort'] == "25") $styleConvert = "Melomel (Fruit Mead)";
if ($row_log['brewCategorySort'] == "26") $styleConvert = "Other Mead";
if ($row_log['brewCategorySort'] == "27") $styleConvert = "Standard Cider and Perry";
if ($row_log['brewCategorySort'] == "28") $styleConvert = "Specialty Cider and Perry";

if ($row_log_winners['brewWinnerCat'] == "01") $styleConvert2 = "Light Lager";
if ($row_log_winners['brewWinnerCat'] == "02") $styleConvert2 = "Pilsner";
if ($row_log_winners['brewWinnerCat'] == "03") $styleConvert2 = "European Amber Lager";
if ($row_log_winners['brewWinnerCat'] == "04") $styleConvert2 = "Dark Lager";
if ($row_log_winners['brewWinnerCat'] == "05") $styleConvert2 = "Bock";
if ($row_log_winners['brewWinnerCat'] == "06") $styleConvert2 = "Light Hybrid Beer";
if ($row_log_winners['brewWinnerCat'] == "07") $styleConvert2 = "Amber Hybrid Beer";
if ($row_log_winners['brewWinnerCat'] == "08") $styleConvert2 = "English Pale Ale";
if ($row_log_winners['brewWinnerCat'] == "09") $styleConvert2 = "Scottish and Irish Ale";
if ($row_log_winners['brewWinnerCat'] == "10") $styleConvert2 = "American Ale";
if ($row_log_winners['brewWinnerCat'] == "11") $styleConvert2 = "English Brown Ale";
if ($row_log_winners['brewWinnerCat'] == "12") $styleConvert2 = "Porter";
if ($row_log_winners['brewWinnerCat'] == "13") $styleConvert2 = "Stout";
if ($row_log_winners['brewWinnerCat'] == "14") $styleConvert2 = "India Pale Ale (IPA)";
if ($row_log_winners['brewWinnerCat'] == "15") $styleConvert2 = "German Wheat and Rye Beer";
if ($row_log_winners['brewWinnerCat'] == "16") $styleConvert2 = "Belgian and French Ale";
if ($row_log_winners['brewWinnerCat'] == "17") $styleConvert2 = "Sour Ale";
if ($row_log_winners['brewWinnerCat'] == "18") $styleConvert2 = "Belgian Strong Ale";
if ($row_log_winners['brewWinnerCat'] == "19") $styleConvert2 = "Strong Ale";
if ($row_log_winners['brewWinnerCat'] == "20") $styleConvert2 = "Fruit Beer";
if ($row_log_winners['brewWinnerCat'] == "21") $styleConvert2 = "Spice/Herb/Vegatable Beer";
if ($row_log_winners['brewWinnerCat'] == "22") $styleConvert2 = "Smoke-Flavored and Wood-Aged Beer";
if ($row_log_winners['brewWinnerCat'] == "23") $styleConvert2 = "Specialty Beer";
if ($row_log_winners['brewWinnerCat'] == "24") $styleConvert2 = "Traditional Mead";
if ($row_log_winners['brewWinnerCat'] == "25") $styleConvert2 = "Melomel (Fruit Mead)";
if ($row_log_winners['brewWinnerCat'] == "26") $styleConvert2 = "Other Mead";
if ($row_log_winners['brewWinnerCat'] == "27") $styleConvert2 = "Standard Cider and Perry";
if ($row_log_winners['brewWinnerCat'] == "28") $styleConvert2 = "Specialty Cider and Perry";

if ($row_bos['brewWinnerCat'] == "01") $styleConvert3 = "Light Lager";
if ($row_bos['brewWinnerCat'] == "02") $styleConvert3 = "Pilsner";
if ($row_bos['brewWinnerCat'] == "03") $styleConvert3 = "European Amber Lager";
if ($row_bos['brewWinnerCat'] == "04") $styleConvert3 = "Dark Lager";
if ($row_bos['brewWinnerCat'] == "05") $styleConvert3 = "Bock";
if ($row_bos['brewWinnerCat'] == "06") $styleConvert3 = "Light Hybrid Beer";
if ($row_bos['brewWinnerCat'] == "07") $styleConvert3 = "Amber Hybrid Beer";
if ($row_bos['brewWinnerCat'] == "08") $styleConvert3 = "English Pale Ale";
if ($row_bos['brewWinnerCat'] == "09") $styleConvert3 = "Scottish and Irish Ale";
if ($row_bos['brewWinnerCat'] == "10") $styleConvert3 = "American Ale";
if ($row_bos['brewWinnerCat'] == "11") $styleConvert3 = "English Brown Ale";
if ($row_bos['brewWinnerCat'] == "12") $styleConvert3 = "Porter";
if ($row_bos['brewWinnerCat'] == "13") $styleConvert3 = "Stout";
if ($row_bos['brewWinnerCat'] == "14") $styleConvert3 = "India Pale Ale (IPA)";
if ($row_bos['brewWinnerCat'] == "15") $styleConvert3 = "German Wheat and Rye Beer";
if ($row_bos['brewWinnerCat'] == "16") $styleConvert3 = "Belgian and French Ale";
if ($row_bos['brewWinnerCat'] == "17") $styleConvert3 = "Sour Ale";
if ($row_bos['brewWinnerCat'] == "18") $styleConvert3 = "Belgian Strong Ale";
if ($row_bos['brewWinnerCat'] == "19") $styleConvert3 = "Strong Ale";
if ($row_bos['brewWinnerCat'] == "20") $styleConvert3 = "Fruit Beer";
if ($row_bos['brewWinnerCat'] == "21") $styleConvert3 = "Spice/Herb/Vegatable Beer";
if ($row_bos['brewWinnerCat'] == "22") $styleConvert3 = "Smoke-Flavored and Wood-Aged Beer";
if ($row_bos['brewWinnerCat'] == "23") $styleConvert3 = "Specialty Beer";
if ($row_bos['brewWinnerCat'] == "24") $styleConvert3 = "Traditional Mead";
if ($row_bos['brewWinnerCat'] == "25") $styleConvert3 = "Melomel (Fruit Mead)";
if ($row_bos['brewWinnerCat'] == "26") $styleConvert3 = "Other Mead";
if ($row_bos['brewWinnerCat'] == "27") $styleConvert3 = "Standard Cider and Perry";
if ($row_bos['brewWinnerCat'] == "28") $styleConvert3 = "Specialty Cider and Perry";

?>