<?php 

if ($row_log['brewCategorySort'] == "01") $styleConvert = "Light Lager";
if ($row_log['brewCategorySort'] == "02") $styleConvert = "Pilsner";
if ($row_log['brewCategorySort'] == "03") $styleConvert = "European Amber Lager";
if ($row_log['brewCategorySort'] == "04") $styleConvert = "Dark Lager";
if ($row_log['brewCategorySort'] == "05") $styleConvert = "Bock";
if ($row_log['brewCategorySort'] == "06") $styleConvert = "Light Hybrid Beer";
if ($row_log['brewCategorySort'] == "07") $styleConvert = "Amber Hybrid Beer";
if ($row_log['brewCategorySort'] == "08") $styleConvert = "English Pale Ale";
if ($row_log['brewCategorySort'] == "09") $styleConvert = "Scottish and Irish Ale";
if ($row_log['brewCategorySort'] == "10") $styleConvert = "American Ale";
if ($row_log['brewCategorySort'] == "11") $styleConvert = "English Brown Ale";
if ($row_log['brewCategorySort'] == "12") $styleConvert = "Porter";
if ($row_log['brewCategorySort'] == "13") $styleConvert = "Stout";
if ($row_log['brewCategorySort'] == "14") $styleConvert = "India Pale Ale (IPA)";
if ($row_log['brewCategorySort'] == "15") $styleConvert = "German Wheat and Rye Beer";
if ($row_log['brewCategorySort'] == "16") $styleConvert = "Belgian and French Ale";
if ($row_log['brewCategorySort'] == "17") $styleConvert = "Sour Ale";
if ($row_log['brewCategorySort'] == "18") $styleConvert = "Belgian Strong Ale";
if ($row_log['brewCategorySort'] == "19") $styleConvert = "Strong Ale";
if ($row_log['brewCategorySort'] == "20") $styleConvert = "Fruit Beer";
if ($row_log['brewCategorySort'] == "21") $styleConvert = "Spice/Herb/Vegatable Beer";
if ($row_log['brewCategorySort'] == "22") $styleConvert = "Smoke-Flavored and Wood-Aged Beer";
if ($row_log['brewCategorySort'] == "23") $styleConvert = "Specialty Beer";
if ($row_log['brewCategorySort'] == "24") $styleConvert = "Traditional Mead";
if ($row_log['brewCategorySort'] == "25") $styleConvert = "Melomel (Fruit Mead)";
if ($row_log['brewCategorySort'] == "26") $styleConvert = "Other Mead";
if ($row_log['brewCategorySort'] == "27") $styleConvert = "Standard Cider and Perry";
if ($row_log['brewCategorySort'] == "28") $styleConvert = "Specialty Cider and Perry";

if ($row_log_winners['brewWinnerCat'] == "01") $styleConvert2 = "Light Lager";
if ($row_log_winners['brewWinnerCat'] == "02") $styleConvert2 = "Pilsner";
if ($row_log_winners['brewWinnerCat'] == "03") $styleConvert2 = "European Amber Lager";
if ($row_log_winners['brewWinnerCat'] == "04") $styleConvert2 = "Dark Lager";
if ($row_log_winners['brewWinnerCat'] == "05") $styleConvert2 = "Bock";
if ($row_log_winners['brewWinnerCat'] == "06") $styleConvert2 = "Light Hybrid Beer";
if ($row_log_winners['brewWinnerCat'] == "07") $styleConvert2 = "Amber Hybrid Beer";
if ($row_log_winners['brewWinnerCat'] == "08") $styleConvert2 = "English Pale Ale";
if ($row_log_winners['brewWinnerCat'] == "09") $styleConvert2 = "Scottish and Irish Ale";
if ($row_log_winners['brewWinnerCat'] == "10") $styleConvert2 = "American Ale";
if ($row_log_winners['brewWinnerCat'] == "11") $styleConvert2 = "English Brown Ale";
if ($row_log_winners['brewWinnerCat'] == "12") $styleConvert2 = "Porter";
if ($row_log_winners['brewWinnerCat'] == "13") $styleConvert2 = "Stout";
if ($row_log_winners['brewWinnerCat'] == "14") $styleConvert2 = "India Pale Ale (IPA)";
if ($row_log_winners['brewWinnerCat'] == "15") $styleConvert2 = "German Wheat and Rye Beer";
if ($row_log_winners['brewWinnerCat'] == "16") $styleConvert2 = "Belgian and French Ale";
if ($row_log_winners['brewWinnerCat'] == "17") $styleConvert2 = "Sour Ale";
if ($row_log_winners['brewWinnerCat'] == "18") $styleConvert2 = "Belgian Strong Ale";
if ($row_log_winners['brewWinnerCat'] == "19") $styleConvert2 = "Strong Ale";
if ($row_log_winners['brewWinnerCat'] == "20") $styleConvert2 = "Fruit Beer";
if ($row_log_winners['brewWinnerCat'] == "21") $styleConvert2 = "Spice/Herb/Vegatable Beer";
if ($row_log_winners['brewWinnerCat'] == "22") $styleConvert2 = "Smoke-Flavored and Wood-Aged Beer";
if ($row_log_winners['brewWinnerCat'] == "23") $styleConvert2 = "Specialty Beer";
if ($row_log_winners['brewWinnerCat'] == "24") $styleConvert2 = "Traditional Mead";
if ($row_log_winners['brewWinnerCat'] == "25") $styleConvert2 = "Melomel (Fruit Mead)";
if ($row_log_winners['brewWinnerCat'] == "26") $styleConvert2 = "Other Mead";
if ($row_log_winners['brewWinnerCat'] == "27") $styleConvert2 = "Standard Cider and Perry";
if ($row_log_winners['brewWinnerCat'] == "28") $styleConvert2 = "Specialty Cider and Perry";

if ($row_bos['brewWinnerCat'] == "01") $styleConvert3 = "Light Lager";
if ($row_bos['brewWinnerCat'] == "02") $styleConvert3 = "Pilsner";
if ($row_bos['brewWinnerCat'] == "03") $styleConvert3 = "European Amber Lager";
if ($row_bos['brewWinnerCat'] == "04") $styleConvert3 = "Dark Lager";
if ($row_bos['brewWinnerCat'] == "05") $styleConvert3 = "Bock";
if ($row_bos['brewWinnerCat'] == "06") $styleConvert3 = "Light Hybrid Beer";
if ($row_bos['brewWinnerCat'] == "07") $styleConvert3 = "Amber Hybrid Beer";
if ($row_bos['brewWinnerCat'] == "08") $styleConvert3 = "English Pale Ale";
if ($row_bos['brewWinnerCat'] == "09") $styleConvert3 = "Scottish and Irish Ale";
if ($row_bos['brewWinnerCat'] == "10") $styleConvert3 = "American Ale";
if ($row_bos['brewWinnerCat'] == "11") $styleConvert3 = "English Brown Ale";
if ($row_bos['brewWinnerCat'] == "12") $styleConvert3 = "Porter";
if ($row_bos['brewWinnerCat'] == "13") $styleConvert3 = "Stout";
if ($row_bos['brewWinnerCat'] == "14") $styleConvert3 = "India Pale Ale (IPA)";
if ($row_bos['brewWinnerCat'] == "15") $styleConvert3 = "German Wheat and Rye Beer";
if ($row_bos['brewWinnerCat'] == "16") $styleConvert3 = "Belgian and French Ale";
if ($row_bos['brewWinnerCat'] == "17") $styleConvert3 = "Sour Ale";
if ($row_bos['brewWinnerCat'] == "18") $styleConvert3 = "Belgian Strong Ale";
if ($row_bos['brewWinnerCat'] == "19") $styleConvert3 = "Strong Ale";
if ($row_bos['brewWinnerCat'] == "20") $styleConvert3 = "Fruit Beer";
if ($row_bos['brewWinnerCat'] == "21") $styleConvert3 = "Spice/Herb/Vegatable Beer";
if ($row_bos['brewWinnerCat'] == "22") $styleConvert3 = "Smoke-Flavored and Wood-Aged Beer";
if ($row_bos['brewWinnerCat'] == "23") $styleConvert3 = "Specialty Beer";
if ($row_bos['brewWinnerCat'] == "24") $styleConvert3 = "Traditional Mead";
if ($row_bos['brewWinnerCat'] == "25") $styleConvert3 = "Melomel (Fruit Mead)";
if ($row_bos['brewWinnerCat'] == "26") $styleConvert3 = "Other Mead";
if ($row_bos['brewWinnerCat'] == "27") $styleConvert3 = "Standard Cider and Perry";
if ($row_bos['brewWinnerCat'] == "28") $styleConvert3 = "Specialty Cider and Perry";


if ($row_styles['brewStyleGroup'] == "01") $styleConvert4 = "Light Lager"; $styleConvert5 = "1A,1B,1C,1D,1E";
if ($row_styles['brewStyleGroup'] == "02") $styleConvert4 = "Pilsner"; $styleConvert5 = "2A,2B,2C,";
if ($row_styles['brewStyleGroup'] == "03") $styleConvert4 = "European Amber Lager"; $styleConvert5 = "3A,3B,";
if ($row_styles['brewStyleGroup'] == "04") $styleConvert4 = "Dark Lager"; $styleConvert5 = "4A,4B,4C,";
if ($row_styles['brewStyleGroup'] == "05") $styleConvert4 = "Bock"; $styleConvert5 = "5A,5B,5C,5D,";
if ($row_styles['brewStyleGroup'] == "06") $styleConvert4 = "Light Hybrid Beer"; $styleConvert5 = "6A,6B,6C,6D,";
if ($row_styles['brewStyleGroup'] == "07") $styleConvert4 = "Amber Hybrid Beer"; $styleConvert5 = "7A,7B,7C,";
if ($row_styles['brewStyleGroup'] == "08") $styleConvert4 = "English Pale Ale"; $styleConvert5 = "8A,8B,8C,";
if ($row_styles['brewStyleGroup'] == "09") $styleConvert4 = "Scottish and Irish Ale"; $styleConvert5 = "9A,9B,9C,9D,9E";
if ($row_styles['brewStyleGroup'] == "10") $styleConvert4 = "American Ale"; $styleConvert5 = "10A,10B,10C,";
if ($row_styles['brewStyleGroup'] == "11") $styleConvert4 = "English Brown Ale"; $styleConvert5 = "11A,11B,11C,";
if ($row_styles['brewStyleGroup'] == "12") $styleConvert4 = "Porter"; $styleConvert5 = "12A,12B,12C,";
if ($row_styles['brewStyleGroup'] == "13") $styleConvert4 = "Stout"; $styleConvert5 = "13A,13B,13C,13D,13E,13F";
if ($row_styles['brewStyleGroup'] == "14") $styleConvert4 = "India Pale Ale (IPA)"; $styleConvert5 = "14A,14B,14C,";
if ($row_styles['brewStyleGroup'] == "15") $styleConvert4 = "German Wheat and Rye Beer"; $styleConvert5 = "15A,15B,15C,15D,";
if ($row_styles['brewStyleGroup'] == "16") $styleConvert4 = "Belgian and French Ale"; $styleConvert5 = "16A,16B,16C,16D,16E,";
if ($row_styles['brewStyleGroup'] == "17") $styleConvert4 = "Sour Ale"; $styleConvert5 = "17A,17B,17C,17D,17E,17F";
if ($row_styles['brewStyleGroup'] == "18") $styleConvert4 = "Belgian Strong Ale"; $styleConvert5 = "18A,18B,18C,18D,18E,";
if ($row_styles['brewStyleGroup'] == "19") $styleConvert4 = "Strong Ale"; $styleConvert5 = "19A,19B,19C,";
if ($row_styles['brewStyleGroup'] == "20") $styleConvert4 = "Fruit Beer" ;$styleConvert5 = "20,";
if ($row_styles['brewStyleGroup'] == "21") $styleConvert4 = "Spice/Herb/Vegetable Beer"; $styleConvert5 = "21A,21B,";
if ($row_styles['brewStyleGroup'] == "22") $styleConvert4 = "Smoke-Flavored and Wood-Aged Beer"; $styleConvert5 = "22A,22B,22C,";
if ($row_styles['brewStyleGroup'] == "23") $styleConvert4 = "Specialty Beer"; $styleConvert5 = "23,";
if ($row_styles['brewStyleGroup'] == "24") $styleConvert4 = "Traditional Mead"; $styleConvert5 = "24A,24B,24C";
if ($row_styles['brewStyleGroup'] == "25") $styleConvert4 = "Melomel (Fruit Mead)"; $styleConvert5 = "25A,25B,25C";
if ($row_styles['brewStyleGroup'] == "26") $styleConvert4 = "Other Mead"; $styleConvert5 = "25A,25B,26C";
if ($row_styles['brewStyleGroup'] == "27") $styleConvert4 = "Standard Cider and Perry"; $styleConvert5 = "27A,27B,27C,27D,27E,";
if ($row_styles['brewStyleGroup'] == "28") $styleConvert4 = "Specialty Cider and Perry"; $styleConvert5 = "28A,28B,28C,28D,";

?>