<?php
$data = array(
  array('brewStyleGroup' => '11','brewStyleNum' => '174','brewStyle' => 'Experimental India Pale Ale','brewStyleCategory' => 'Hybrid/Mixed Lagers or Ales','brewStyleVersion' => 'BA','brewStyleOG' => '1.06','brewStyleOGMax' => '1.1','brewStyleFG' => '0.994','brewStyleFGMax' => '1.02','brewStyleABV' => '6.3','brewStyleABVMax' => '10.6','brewStyleIBU' => '30','brewStyleIBUMax' => '100','brewStyleSRM' => '4','brewStyleSRMMax' => '40','brewStyleType' => '1','brewStyleInfo' => 'Beers in this category recognize the cutting edge of American IPA brewing. Experimental India Pale Ales are either 1) any of White, Red, Brown, Brut or many other IPA or Imperial IPA types or combinations thereof currently in production, and fruited or spiced versions of these, or 2) fruited or spiced versions of classic American, Juicy Hazy, and Imperial IPA categories. They range widely in color, hop and malt intensity and attributes, hop bitterness, balance, alcohol content, body and overall flavor experience. ','brewStyleLink' => 'https://www.brewersassociation.org/edu/brewers-association-beer-style-guidelines/','brewStyleActive' => 'N','brewStyleOwn' => 'bcoe','brewStyleReqSpec' => '1','brewStyleStrength' => '0','brewStyleCarb' => '0','brewStyleSweet' => '0','brewStyleTags' => '2020','brewStyleComEx' => '','brewStyleEntry' => NULL),
  array('brewStyleGroup' => '03','brewStyleNum' => '175','brewStyle' => 'Juicy or Hazy Strong Pale Ale','brewStyleCategory' => 'North American Origin Ales','brewStyleVersion' => 'BA','brewStyleOG' => '1.05','brewStyleOGMax' => '1.065','brewStyleFG' => '1.008','brewStyleFGMax' => '1.016','brewStyleABV' => '5.6','brewStyleABVMax' => '7','brewStyleIBU' => '40','brewStyleIBUMax' => '50','brewStyleSRM' => '4','brewStyleSRMMax' => '9','brewStyleType' => '1','brewStyleInfo' => 'Grist may include oats, wheat or other adjuncts to promote haziness. The term "juicy" is frequently used to describe taste and aroma attributes often present in these beers which result from late, often very large, additions of hops. A juicy character is not required, however. Other hopderived attributes such as citrus, pine, spice, floral or others may be present with or without the presence of juicy attributes.','brewStyleLink' => 'https://www.brewersassociation.org/edu/brewers-association-beer-style-guidelines/','brewStyleActive' => 'N','brewStyleOwn' => 'bcoe','brewStyleReqSpec' => '0','brewStyleStrength' => '0','brewStyleCarb' => '0','brewStyleSweet' => '0','brewStyleTags' => '2020','brewStyleComEx' => '','brewStyleEntry' => NULL),
  array('brewStyleGroup' => '05','brewStyleNum' => '176','brewStyle' => 'Contemporary Belgian-Style Gueuze Lambic','brewStyleCategory' => 'Belgian And French Origin Ales','brewStyleVersion' => 'BA','brewStyleOG' => '1.044','brewStyleOGMax' => '1.056','brewStyleFG' => '1','brewStyleFGMax' => '1.01','brewStyleABV' => '5','brewStyleABVMax' => '8.9','brewStyleIBU' => '11','brewStyleIBUMax' => '23','brewStyleSRM' => '6','brewStyleSRMMax' => '40','brewStyleType' => '1','brewStyleInfo' => 'Gueuze Lambics, whose origin is the Brussels area of Belgium, are often simply called Gueuze Lambic. Versions of this beer style made outside of the Brussels area are said to be "BelgianStyle Gueuze Lambics." The Belgian-style versions are made to resemble many of the beers of true origin. While Traditional Gueuze Lambics are dry, Contemporary Gueuze Lambics may have a degree of sweetness contributed by sugars or other sweeteners. Traditionally, Gueuze is brewed with unmalted wheat, malted barley, and stale, aged hops. Whereas Contemporary Gueuze Lambics may incorporate specialty malts that influence the hue, flavor and aroma of the finished beer.','brewStyleLink' => 'https://www.brewersassociation.org/edu/brewers-association-beer-style-guidelines/','brewStyleActive' => 'N','brewStyleOwn' => 'bcoe','brewStyleReqSpec' => '0','brewStyleStrength' => '0','brewStyleCarb' => '0','brewStyleSweet' => '0','brewStyleTags' => '2020','brewStyleComEx' => '','brewStyleEntry' => NULL),
  array('brewStyleGroup' => '07','brewStyleNum' => '177','brewStyle' => 'Franconian-Style Rotbier','brewStyleCategory' => 'European Origin Lagers','brewStyleVersion' => 'BA','brewStyleOG' => '1.046','brewStyleOGMax' => '1.056','brewStyleFG' => '1.008','brewStyleFGMax' => '1.01','brewStyleABV' => '4.8','brewStyleABVMax' => '5.6','brewStyleIBU' => '20','brewStyleIBUMax' => '28','brewStyleSRM' => '13','brewStyleSRMMax' => '23','brewStyleType' => '1','brewStyleInfo' => '','brewStyleLink' => 'https://www.brewersassociation.org/edu/brewers-association-beer-style-guidelines/','brewStyleActive' => 'N','brewStyleOwn' => 'bcoe','brewStyleReqSpec' => '0','brewStyleStrength' => '0','brewStyleCarb' => '0','brewStyleSweet' => '0','brewStyleTags' => '2020','brewStyleComEx' => '','brewStyleEntry' => NULL),
  array('brewStyleGroup' => '08','brewStyleNum' => '179','brewStyle' => 'Contemporary American-Style Lager','brewStyleCategory' => 'North American Origin Lagers','brewStyleVersion' => 'BA','brewStyleOG' => '1.04','brewStyleOGMax' => '1.048','brewStyleFG' => '1.006','brewStyleFGMax' => '1.012','brewStyleABV' => '4.1','brewStyleABVMax' => '5.1','brewStyleIBU' => '5','brewStyleIBUMax' => '19','brewStyleSRM' => '2','brewStyleSRMMax' => '4','brewStyleType' => '1','brewStyleInfo' => 'Corn, rice, or other grain or sugar adjuncts are often used, but all-malt formulations are also made. Contemporary American Lagers typically exhibit increased hop aroma and flavor compared to traditional versions, are clean and crisp, and aggressively carbonated.','brewStyleLink' => 'https://www.brewersassociation.org/edu/brewers-association-beer-style-guidelines/','brewStyleActive' => 'N','brewStyleOwn' => 'bcoe','brewStyleReqSpec' => '0','brewStyleStrength' => '0','brewStyleCarb' => '0','brewStyleSweet' => '0','brewStyleTags' => '2020','brewStyleComEx' => '','brewStyleEntry' => NULL),
  array('brewStyleGroup' => '08','brewStyleNum' => '180','brewStyle' => 'Contemporary American-Style Light Lager','brewStyleCategory' => 'North American Origin Lagers','brewStyleVersion' => 'BA','brewStyleOG' => '1.024','brewStyleOGMax' => '1.04','brewStyleFG' => '0.992','brewStyleFGMax' => '1.008','brewStyleABV' => '3.5','brewStyleABVMax' => '4.4','brewStyleIBU' => '4','brewStyleIBUMax' => '15','brewStyleSRM' => '1.5','brewStyleSRMMax' => '12','brewStyleType' => '1','brewStyleInfo' => 'Corn, rice or other grain or sugar adjuncts may be used but all-malt formulations are also made. These beers are high in carbonation. Hop attributes, though subtle, are more evident than in traditional American-Style Light Lager. Calories should not exceed 125 per 12-ounce serving. Low carb beers should have a maximum carbohydrate level of 3.0 gm per 12 oz. (355 ml).','brewStyleLink' => 'https://www.brewersassociation.org/edu/brewers-association-beer-style-guidelines/','brewStyleActive' => 'N','brewStyleOwn' => 'bcoe','brewStyleReqSpec' => '0','brewStyleStrength' => '0','brewStyleCarb' => '0','brewStyleSweet' => '0','brewStyleTags' => '2020','brewStyleComEx' => '','brewStyleEntry' => NULL)
);

$update_table = $prefix."styles";
// Insert per-row (not insertMulti()) and skip any style that already exists -
// a blind bulk insert here can re-duplicate this entire batch if this script
// runs again against a DB state where the check_new_style() guard in
// run_update.php (which only checks one sentinel style) doesn't catch that
// most/all of the batch is already present. See styles_aabc_2022_update.php.
$inserted = 0;
$skipped = 0;
$insert_errors = FALSE;
foreach ($data as $row) {
  if (check_new_style($row['brewStyleGroup'], $row['brewStyleNum'], $row['brewStyle'])) {
    $skipped++;
    continue;
  }
  if ($db_conn->insert($update_table, $row)) $inserted++;
  else {
    $insert_errors = TRUE;
    $output_run_update .= "<li>Addition of ".$row['brewStyle']." failed. <strong class=\"text-danger\">Error: ".$db_conn->getLastError()."</strong></li>";
    $error_count += 1;
  }
}
if ($inserted > 0) $output_run_update .= "<li>Added ".$inserted." new 2020 BA Styles to styles table".(($skipped > 0) ? " (".$skipped." already present, skipped)" : "").".</li>";
elseif (!$insert_errors) $output_run_update .= "<li>2020 BA Styles already present in styles table - nothing to add.</li>";

?>