<?php
declare(strict_types=1);

/**
 * Generates typed Repository classes from the table list.
 *
 * Usage: php tools/generate_repositories.php
 * Writes: src/Repository/<Table>Repository.php (one per table)
 *
 * Each repository extends AbstractRepository<TRow>, declares the table name,
 * and hydrates rows to the matching Domain Row class.
 */

const REPO_OUTPUT_DIR = __DIR__ . '/../src/Repository';

/** @var list<array{table: string, class: string}> */
$tables = [
    ['table' => 'archive',              'class' => 'ArchiveRow'],
    ['table' => 'bcoem_sys',            'class' => 'BcoemSysRow'],
    ['table' => 'brewer',               'class' => 'BrewerRow'],
    ['table' => 'brewing',              'class' => 'BrewingRow'],
    ['table' => 'contacts',             'class' => 'ContactsRow'],
    ['table' => 'contest_info',         'class' => 'ContestInfoRow'],
    ['table' => 'drop_off',             'class' => 'DropOffRow'],
    ['table' => 'evaluation',           'class' => 'EvaluationRow'],
    ['table' => 'judging_assignments',  'class' => 'JudgingAssignmentsRow'],
    ['table' => 'judging_flights',      'class' => 'JudgingFlightsRow'],
    ['table' => 'judging_locations',    'class' => 'JudgingLocationsRow'],
    ['table' => 'judging_preferences',  'class' => 'JudgingPreferencesRow'],
    ['table' => 'judging_scores',       'class' => 'JudgingScoresRow'],
    ['table' => 'judging_scores_bos',   'class' => 'JudgingScoresBosRow'],
    ['table' => 'judging_tables',       'class' => 'JudgingTablesRow'],
    ['table' => 'mods',                 'class' => 'ModsRow'],
    ['table' => 'preferences',          'class' => 'PreferencesRow'],
    ['table' => 'special_best_data',    'class' => 'SpecialBestDataRow'],
    ['table' => 'special_best_info',    'class' => 'SpecialBestInfoRow'],
    ['table' => 'sponsors',             'class' => 'SponsorsRow'],
    ['table' => 'staff',                'class' => 'StaffRow'],
    ['table' => 'styles',               'class' => 'StylesRow'],
    ['table' => 'style_types',          'class' => 'StyleTypesRow'],
    ['table' => 'users',                'class' => 'UsersRow'],
];

$count = 0;
foreach ($tables as $t) {
    $repoClass = tableToClassName($t['table']) . 'Repository';
    $php = renderRepo($repoClass, $t['table'], $t['class']);
    $outFile = REPO_OUTPUT_DIR . '/' . $repoClass . '.php';
    file_put_contents($outFile, $php);
    $count++;
    echo "generated {$outFile}\n";
}

echo "\n{$count} repositories written to " . REPO_OUTPUT_DIR . "\n";

function tableToClassName(string $table): string
{
    return str_replace(' ', '', ucwords(str_replace('_', ' ', $table)));
}

function renderRepo(string $repoClass, string $table, string $rowClass): string
{
    return <<<PHP
<?php
declare(strict_types=1);

namespace BCOEM\\Repository;

use BCOEM\\Domain\\{$rowClass};

/**
 * Typed repository for table `{$table}`.
 * Generated by tools/generate_repositories.php — do not edit by hand.
 *
 * @extends AbstractRepository<{$rowClass}>
 */
final class {$repoClass} extends AbstractRepository
{
    protected function table(): string
    {
        return '{$table}';
    }

    /**
     * @param array<string, mixed> \$row
     */
    protected function hydrate(array \$row): object
    {
        return {$rowClass}::fromArray(\$row);
    }
}

PHP;
}
